### ISSUE TITLE
outdated Salmon

### ISSUE THREAD

**Issue by rkhetani** [hbctraining/Intro-to-rnaseq-hpc-salmon#3]
Jihe was running through the workshop materials and found that the index from february was not working for Salmon. Looks like there was an update to the Salmon version on bcbio creating this problem.

So, I have created a new index called `salmon.ensembl38.idx.09-06-2019/` in `/n/groups/hbctraining/rna-seq_2019_02/reference_data/` and we need to update the salmon lesson ASAP.

**Comment by jihe-liu** [comment]
The error message using the old index is: "I found a quasi-index with version q5, but I require q6. Please re-index the reference."
Salmon runs successfully using the updated index.

**Comment by mistrm82** [comment]
changed in the salmon lesson and in automation thanks @jihe-liu
